/* Action types */
export const actionTypes = {
    LISTINGS_SOAR_INFO_FETCH: 'LISTINGS/SOAR_INFO_FETCH',
    LISTINGS_SOAR_INFO_FETCH_SUCCESS: 'LISTINGS/SOAR_INFO_FETCH_SUCCESS',
    LISTINGS_EVENT_UPLOADED: 'LISTINGS/EVENT_UPLOADED',
    LISTINGS_EVENT_UPLOADED_SUCCESS: 'LISTINGS/EVENT_UPLOADED_SUCCESS',
    LISTINGS_PRICE_UPDATE: 'LISTINGS/PRICE_UPDATE',
    LISTINGS_PRICE_UPDATE_SUCCESS: 'LISTINGS/PRICE_UPDATE_SUCCESS'
};
