/* Action types */
export const actionTypes = {
    NOTIFICATIONS_PROGRESS_MESSAGE: 'NOTIFICATIONS/PROGRESS_MESSAGE',
    NOTIFICATIONS_PROGRESS_MESSAGE_DONE: 'NOTIFICATIONS/PROGRESS_MESSAGE_DONE'
};
