/* Action types */
export const actionTypes = {
    NOTIFICATIONS_PROGRESS_MESSAGE: 'NOTIFICATIONS/PROGRESS_MESSAGE',
    NOTIFICATIONS_PROGRESS_MESSAGE_DONE: 'NOTIFICATIONS/PROGRESS_MESSAGE_DONE',
    NOTIFICATIONS_USER_INFO: 'NOTIFICATIONS/USER_INFO',
    NOTIFICATIONS_USER_INFO_SUCCESS: 'NOTIFICATIONS/USER_INFO_SUCCESS',
    
};
