/* Action types */
export const actionTypes = {
    TOKEN_INFO_FETCH: 'TOKEN/INFO_FETCH',
    TOKEN_INFO_FETCH_SUCCESS: 'TOKEN/INFO_FETCH_SUCCESS',
    TOKEN_INFO_FETCH_ERROR: 'TOKEN/INFO_FETCH_ERROR',
    FAUCET_GET_SKYM: 'FAUCET/GET_SKYM'
};
