/* Action types */
export const actionTypes = {
    FAUCET_ADMIN_INFO_FETCH: 'FAUCET_ADMIN_/INFO_FETCH',
    FAUCET_ADMIN_INFO_FETCH_SUCCESS: 'FAUCET_ADMIN_/INFO_FETCH_SUCCESS',
    FAUCET_ADMIN_INFO_FETCH_ERROR: 'FAUCET_ADMIN_/INFO_FETCH_ERROR',
    FAUCET_ADMIN_SET_TOKEN_CONTRACT: 'FAUCET_ADMIN_/SET_TOKEN_CONTRACT',
    FAUCET_ADMIN_SET_ALLOWANCE: 'FAUCET_ADMIN_/SET_ALLOWANCE',
    FAUCET_ADMIN_SET_WAITING_PERIOD: 'FAUCET_ADMIN_/SET_WAITING_PERIOD',
    FAUCET_ADMIN_SET_INDIVIDUAL_CAP: 'FAUCET_ADMIN_/SET_INDIVIDUAL_CAP'
};
