/* Action types */
export const actionTypes = {
    ADMIN_INFO_FETCH: 'ADMIN/INFO_FETCH',
    ADMIN_INFO_FETCH_SUCCESS: 'ADMIN/INFO_FETCH_SUCCESS',
    ADMIN_INFO_FETCH_ERROR: 'ADMIN/INFO_FETCH_ERROR',
    FAUCET_SET_TOKEN_CONTRACT: 'FAUCET/SET_TOKEN_CONTRACT',
    FAUCET_SET_ALLOWANCE: 'FAUCET/SET_ALLOWANCE',
    FAUCET_SET_WAITING_PERIOD: 'FAUCET/SET_WAITING_PERIOD',
    FAUCET_SET_INDIVIDUAL_CAP: 'FAUCET/SET_INDIVIDUAL_CAP'
};
