export const SYSTEM_ERROR = 'SYSTEM_ERROR';

// for MetaMask
export const METAMASK_ACCOUNT = 'METAMASK_ACCOUNT';
export const METAMASK_NETWORK = 'METAMASK_NETWORK';

// for Soar contract
export const SOAR_FILE_COUNTS = 'SOAR_FILE_COUNTS';
export const SOAR_FILE_COUNTS_SUCCESS = 'SOAR_FILE_COUNTS_SUCCESS';
export const SOAR_FILE_UPLOAD = 'SOAR_FILE_UPLOAD';
export const SOAR_FILE_UPLOAD_SUCCESS = 'SOAR_FILE_UPLOAD_SUCCESS';
export const SOAR_FILE_PURCHASE = 'SOAR_FILE_PURCHASE';
export const SOAR_FILE_PURCHASE_SUCCESS = 'SOAR_FILE_PURCHASE_SUCCESS';
export const SOAR_FILE_DOWNLOAD = 'SOAR_FILE_DOWNLOAD';
export const SOAR_FILE_DOWNLOAD_SUCCESS = 'SOAR_FILE_DOWNLOAD_SUCCESS';
export const SOAR_EVENT_UPLOAD = 'SOAR_EVENT_UPLOAD';
export const SOAR_EVENT_MY_SALE = 'SOAR_EVENT_MY_SALE';
export const SOAR_FILE_PRICE = 'SOAR_FILE_PRICE';
export const SOAR_FILE_PRICE_SUCCESS = 'SOAR_FILE_PRICE_SUCCESS';

// for progress bar with text
export const PROGRESS_TEXT = 'PROGRESS_TEXT';
export const PROGRESS_COMPLETE = 'PROGRESS_COMPLETE';


// for showing progress/onloading
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

// for showing system message
export const MESSAGE_INFO = 'MESSAGE_INFO';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_WARNING = 'MESSAGE_WARNING';
export const MESSAGE_CLOSE = 'MESSAGE_CLOSE';
